# Default values for docker-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy:
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

podAnnotations: {}

image:
  repository: 47.104.65.202/xuefeng/pipeline-httpserver
  tag: 31
  pullPolicy: IfNotPresent
# imagePullSecrets:
    # - name: docker
service:
  name: pipeline-httpserver-service
  type: NodePort
  # clusterIP:
  port: 8080
  targetport: 8080
  # nodePort:
  annotations: {}
  # foo.io/bar: "true"
